import fs from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";
import { buildInvestigatePrompt } from "../agents/shared.js";
import { assemblePrompt } from "../prompt/assemble.js";
import { languagesForBatch } from "../prompt/file-language.js";
import { PROMPT_SAMPLE_SCENARIOS, scenarioBatch } from "./prompt-samples.fixtures.js";

const SAMPLES_DIR = path.resolve(import.meta.dirname, "../../../../prompt-samples");

/**
 * Build the FULL prompt that goes to the model for a scenario.
 *
 * Mirrors what `process()` does at runtime:
 *   1. `detectTech()` produces the project-level tag list (here, scenario.detectedTags).
 *   2. `assemblePrompt()` builds the system-prompt half — core + tech
 *      highlights filtered by the batch's languages + per-slug notes for
 *      slugs in the batch + INFO.md + promptAppend.
 *   3. `buildInvestigatePrompt()` (in `agents/shared.ts`) wraps that with
 *      the actual file list, per-file investigation steps, and the JSON
 *      output spec.
 *
 * `projectInfo` is passed to the assembler (not the agent layer) — at
 * runtime the agent layer gets `""` from `process()` to avoid emitting
 * INFO.md twice. We mirror that here.
 */
function fullPromptFor(scenario: (typeof PROMPT_SAMPLE_SCENARIOS)[number]): string {
  const batch = scenarioBatch(scenario);
  const batchSlugs = Array.from(new Set(batch.flatMap((r) => r.candidates.map((c) => c.vulnSlug))));
  const batchLanguages = languagesForBatch(batch.map((r) => r.filePath));
  const { prompt: assembled } = assemblePrompt({
    detectedTags: scenario.detectedTags,
    batchSlugs,
    batchLanguages,
    projectInfo: scenario.projectInfo,
    promptAppend: scenario.promptAppend,
  });
  return buildInvestigatePrompt({
    promptTemplate: assembled,
    projectInfo: "",
    batch,
  });
}

function renderSample(scenario: (typeof PROMPT_SAMPLE_SCENARIOS)[number], prompt: string): string {
  const batch = scenarioBatch(scenario);
  const batchLanguages = languagesForBatch(batch.map((r) => r.filePath));
  const batchSlugs = Array.from(new Set(batch.flatMap((r) => r.candidates.map((c) => c.vulnSlug))));
  return [
    `<!--`,
    `  Scenario: ${scenario.name}`,
    `  ${scenario.description}`,
    `  Detected tags : ${JSON.stringify(scenario.detectedTags)}`,
    `  Batch files   : ${JSON.stringify(scenario.files.map((f) => f.path))}`,
    `  Batch langs   : ${JSON.stringify(batchLanguages)}`,
    `  Batch slugs   : ${JSON.stringify(batchSlugs)}`,
    `  Generated by  : packages/processor/src/__tests__/prompt-samples.test.ts`,
    `  Regenerate    : UPDATE_PROMPT_SAMPLES=1 pnpm test:unit`,
    `-->`,
    "",
    prompt,
    "",
  ].join("\n");
}

describe("prompt-samples/ fixtures stay in sync with the assembler + agent layer", () => {
  // When set, the test rewrites the fixtures on disk instead of asserting.
  // Use this whenever the assembler, highlights, or agent layer
  // intentionally change shape — review the diff in the PR.
  const updating = process.env.UPDATE_PROMPT_SAMPLES === "1";

  if (updating) {
    fs.mkdirSync(SAMPLES_DIR, { recursive: true });
  }

  for (const scenario of PROMPT_SAMPLE_SCENARIOS) {
    it(scenario.name, () => {
      const prompt = fullPromptFor(scenario);
      const expected = renderSample(scenario, prompt);
      const file = path.join(SAMPLES_DIR, `${scenario.name}.md`);

      if (updating) {
        fs.writeFileSync(file, expected);
        return;
      }

      expect(fs.existsSync(file), `missing fixture: ${file}`).toBe(true);
      const onDisk = fs.readFileSync(file, "utf-8");
      expect(onDisk).toBe(expected);
    });
  }

  it("samples include both halves: assembled core AND agent-layer file list", () => {
    const sample = fullPromptFor(PROMPT_SAMPLE_SCENARIOS[1]); // 02-nextjs-tsx-batch
    expect(sample).toContain("## Severity Classification"); // from core
    expect(sample).toContain("### Next.js"); // from highlights
    expect(sample).toContain("## Target Files"); // from agent layer
    expect(sample).toContain("## Output Format"); // from agent layer
    expect(sample).toContain("app/dashboard/actions.ts"); // from the synthetic batch
  });

  it("INFO.md appears exactly once in the final prompt", () => {
    const sample = fullPromptFor(PROMPT_SAMPLE_SCENARIOS[7]); // 08-with-info-and-append
    const occurrences = sample.split("Auth helper is `requireUser()`").length - 1;
    expect(occurrences, "expected INFO.md content exactly once").toBe(1);
  });
});
